services:
  db:
    container_name: postgres-db
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - /Users/trihoang/Desktop/movie_recommender/data:/var/container_files:ro
      - /Users/trihoang/Desktop/movie_recommender/data/movies_series.csv:/docker-entrypoint-initdb.d/movies_series.csv:ro
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  recommender-lambda:
    container_name: recommender-lambda
    image: recommend-lambda-image
    build:
      context: .
      dockerfile: Dockerfile.recommend  # or path to your lambda Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: admin
      DB_PASSWORD: password
      PORT: 5432
      TABLE: movies_series
      MODEL_PATH: /var/task/finetuned_model
    depends_on:
      - db
    ports:
      - "9000:8080" 
    command: ["recommend.lambda_handler"]
  
  search-lambda:
    container_name: search-lambda
    image: search-lambda-image
    build:
      context: .
      dockerfile: Dockerfile.search
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: admin
      DB_PASSWORD: password
      PORT: 5432
      TABLE: movies_series
    depends_on:
      - db
    ports:
      - "9001:8080" 
    command: ["search.lambda_handler"]

volumes:
  postgres-data:
